### ISSUE TITLE
Crashes at random ego gift selection

### ISSUE THREAD

**Issue by Sannann** [Samsterr/sir-squirrel-assistant#38]
For some reason it cant properly get through the random ego gift selection screen at the start of a mirror dungeon run. 
No idea what causes this. Happens in borderless fullscreen and in the proper windowed. 
"Traceback (most recent call last):
  File "sirsquirrel.py", line 63, in <module>
  File "sirsquirrel.py", line 60, in main
  File "sirsquirrel.py", line 39, in mirror_dungeon_run
  File "src\mirror.py", line 91, in start_mirror
  File "src\mirror.py", line 147, in gift_selection
  File "src\mirror.py", line 29, in set_sinner_order
  File "src\common.py", line 262, in squad_order
KeyError: 'default'
[PYI-20920:ERROR] Failed to execute script 'sirsquirrel' due to unhandled exception!"

In the log theres nothing interesting:
"2024-11-01 23:57:00,328 - src.core - INFO - Navigating to Mirror Dungeon
2024-11-01 23:57:04,754 - __main__ - INFO - Current Team: slash
2024-11-01 23:57:09,563 - src.mirror - INFO - E.G.O Gift Selection"

**Comment by Samsterr** [comment]
@Sannann your issue is due to your squad_order.json file missing the entry for default. do not delete anything in the file
